"""Initial migration

Revision ID: 96b063a4c46a
Revises: 
Create Date: 2026-03-26 04:29:59.674970

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96b063a4c46a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False, comment='node, way, relation'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('admin_level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Parent admin boundary'),
    sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='All OSM tags as JSON'),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_administrative_boundaries_geometry', 'administrative_boundaries', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_administrative_boundaries_admin_level'), 'administrative_boundaries', ['admin_level'], unique=False)
    op.create_index(op.f('ix_administrative_boundaries_id'), 'administrative_boundaries', ['id'], unique=False)
    op.create_index(op.f('ix_administrative_boundaries_name'), 'administrative_boundaries', ['name'], unique=False)
    op.create_index(op.f('ix_administrative_boundaries_osm_id'), 'administrative_boundaries', ['osm_id'], unique=True)
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True, comment='residential, commercial, school, hospital, etc.'),
    sa.Column('addr_street', sa.String(length=255), nullable=True),
    sa.Column('addr_housenumber', sa.String(length=50), nullable=True),
    sa.Column('addr_district', sa.String(length=100), nullable=True),
    sa.Column('levels', sa.Integer(), nullable=True, comment='Number of floors'),
    sa.Column('height', sa.Float(), nullable=True, comment='Height in meters'),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area', sa.Float(), nullable=True, comment='Area in square meters'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buildings_geometry', 'buildings', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_buildings_building_type'), 'buildings', ['building_type'], unique=False)
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_index(op.f('ix_buildings_name'), 'buildings', ['name'], unique=False)
    op.create_index(op.f('ix_buildings_osm_id'), 'buildings', ['osm_id'], unique=True)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('responsible_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of category codes'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location_geom', geoalchemy2.types.Geometry(srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_location_geom', 'entities', ['location_geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_location_geom'), 'entities', ['location_geom'], unique=False)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('environmental_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False, comment='air_quality, weather, noise, traffic'),
    sa.Column('value', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Giá trị đo được'),
    sa.Column('unit', sa.String(length=20), nullable=True, comment='Đơn vị: µg/m³, °C, dB, km/h'),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, comment='Thời điểm đo'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='waqi, openweathermap, google_maps'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Thông tin chi tiết: PM2.5, PM10, humidity, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environmental_data_data_type'), 'environmental_data', ['data_type'], unique=False)
    op.create_index(op.f('ix_environmental_data_district_id'), 'environmental_data', ['district_id'], unique=False)
    op.create_index(op.f('ix_environmental_data_id'), 'environmental_data', ['id'], unique=False)
    op.create_index(op.f('ix_environmental_data_measured_at'), 'environmental_data', ['measured_at'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('TRAFFIC', 'WEATHER', 'ENVIRONMENTAL', 'INFRASTRUCTURE', 'PUBLIC_SAFETY', 'UTILITY', name='incidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity'), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True, comment='system, user_report, external_api'),
    sa.Column('source_id', sa.String(length=255), nullable=True, comment='ID from source system'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('affected_area_radius', sa.Float(), nullable=True, comment='Radius in meters'),
    sa.Column('estimated_impact', sa.Integer(), nullable=True, comment='Number of people affected'),
    sa.Column('incident_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra incident data'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_location', 'incidents', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_is_active'), 'incidents', ['is_active'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_started_at'), 'incidents', ['started_at'], unique=False)
    op.create_index(op.f('ix_incidents_title'), 'incidents', ['title'], unique=False)
    op.create_index(op.f('ix_incidents_type'), 'incidents', ['type'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REPORT_STATUS_UPDATE', 'REPORT_COMMENT', 'REPORT_UPVOTE', 'REPORT_ASSIGNED', 'SYSTEM_ANNOUNCEMENT', 'ACHIEVEMENT_UNLOCKED', name='notificationtype'), nullable=False),
    sa.Column('title_template', sa.String(length=255), nullable=False, comment="e.g. 'Báo cáo #{report_id} đã {status}'"),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('email_subject_template', sa.String(length=255), nullable=True),
    sa.Column('email_body_template', sa.Text(), nullable=True),
    sa.Column('push_title_template', sa.String(length=255), nullable=True),
    sa.Column('push_body_template', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_index(op.f('ix_notification_templates_type'), 'notification_templates', ['type'], unique=True)
    op.create_table('pois',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False, comment='amenity, shop, tourism, leisure, etc.'),
    sa.Column('subcategory', sa.String(length=50), nullable=True, comment='restaurant, hospital, atm, hotel, etc.'),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pois_location', 'pois', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_pois_category'), 'pois', ['category'], unique=False)
    op.create_index(op.f('ix_pois_id'), 'pois', ['id'], unique=False)
    op.create_index(op.f('ix_pois_name'), 'pois', ['name'], unique=False)
    op.create_index(op.f('ix_pois_osm_id'), 'pois', ['osm_id'], unique=True)
    op.create_index(op.f('ix_pois_subcategory'), 'pois', ['subcategory'], unique=False)
    op.create_table('public_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False, comment='hospital, school, park, police_station, fire_station, library, market'),
    sa.Column('subcategory', sa.String(length=50), nullable=True, comment='Chi tiết: primary_school, general_hospital'),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('opening_hours', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='Sức chứa'),
    sa.Column('rating', sa.DECIMAL(precision=2, scale=1), nullable=True, comment='Đánh giá 0-5'),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True, comment='osm, gov, manual'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_public_facilities_location', 'public_facilities', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_public_facilities_category'), 'public_facilities', ['category'], unique=False)
    op.create_index(op.f('ix_public_facilities_id'), 'public_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_public_facilities_name'), 'public_facilities', ['name'], unique=False)
    op.create_index(op.f('ix_public_facilities_osm_id'), 'public_facilities', ['osm_id'], unique=True)
    op.create_table('report_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name_vi', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['report_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_categories_code'), 'report_categories', ['code'], unique=True)
    op.create_index(op.f('ix_report_categories_id'), 'report_categories', ['id'], unique=False)
    op.create_table('streets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.BigInteger(), nullable=False),
    sa.Column('osm_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('highway_type', sa.String(length=50), nullable=False, comment='primary, secondary, residential, footway, etc.'),
    sa.Column('surface', sa.String(length=50), nullable=True, comment='asphalt, concrete, unpaved'),
    sa.Column('lanes', sa.Integer(), nullable=True),
    sa.Column('maxspeed', sa.Integer(), nullable=True, comment='km/h'),
    sa.Column('oneway', sa.Boolean(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('length', sa.Float(), nullable=True, comment='Length in meters'),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_streets_geometry', 'streets', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_streets_highway_type'), 'streets', ['highway_type'], unique=False)
    op.create_index(op.f('ix_streets_id'), 'streets', ['id'], unique=False)
    op.create_index(op.f('ix_streets_name'), 'streets', ['name'], unique=False)
    op.create_index(op.f('ix_streets_osm_id'), 'streets', ['osm_id'], unique=True)
    op.create_table('transport_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('osm_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('facility_type', sa.String(length=50), nullable=False, comment='bus_stop, metro_station, taxi_stand, parking'),
    sa.Column('line_number', sa.String(length=20), nullable=True, comment='Số tuyến xe buýt/metro'),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transport_facilities_location', 'transport_facilities', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_transport_facilities_facility_type'), 'transport_facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_transport_facilities_id'), 'transport_facilities', ['id'], unique=False)
    op.create_index(op.f('ix_transport_facilities_osm_id'), 'transport_facilities', ['osm_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'MODERATOR', 'ADMIN', 'GOVERNMENT', name='userrole'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='Email verified'),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True, comment='Phường/xã cư trú'),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('reports_count', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_location', 'users', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('department_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True, comment='manager, member, viewer'),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_members_department_id'), 'department_members', ['department_id'], unique=False)
    op.create_index(op.f('ix_department_members_id'), 'department_members', ['id'], unique=False)
    op.create_index(op.f('ix_department_members_user_id'), 'department_members', ['user_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'DOCUMENT', name='mediatype'), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='Path in storage system'),
    sa.Column('storage_type', sa.String(length=50), nullable=True, comment='local, s3, cloudinary'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Size in bytes'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Image/video width'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Image/video height'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='Video duration in seconds'),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_created_at'), 'media_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_files_file_type'), 'media_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_media_files_id'), 'media_files', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('related_facility_id', sa.Integer(), nullable=True),
    sa.Column('related_street_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'DUPLICATE', name='reportstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='reportpriority'), nullable=False),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('report_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_location', 'reports', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_reports_category'), 'reports', ['category'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('enable_email', sa.Boolean(), nullable=True),
    sa.Column('enable_push', sa.Boolean(), nullable=True),
    sa.Column('enable_sms', sa.Boolean(), nullable=True),
    sa.Column('notify_status_update', sa.Boolean(), nullable=True),
    sa.Column('notify_comments', sa.Boolean(), nullable=True),
    sa.Column('notify_upvotes', sa.Boolean(), nullable=True),
    sa.Column('notify_assignments', sa.Boolean(), nullable=True),
    sa.Column('notify_announcements', sa.Boolean(), nullable=True),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True, comment='HH:MM format'),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True, comment='HH:MM format'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_settings_id'), 'user_notification_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('REPORT_STATUS_UPDATE', 'REPORT_COMMENT', 'REPORT_UPVOTE', 'REPORT_ASSIGNED', 'SYSTEM_ANNOUNCEMENT', 'ACHIEVEMENT_UNLOCKED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_report_id', sa.UUID(), nullable=True),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Extra notification data'),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('report_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_activities_id'), 'report_activities', ['id'], unique=False)
    op.create_index(op.f('ix_report_activities_report_id'), 'report_activities', ['report_id'], unique=False)
    op.create_table('report_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='Specific user in department'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='assignmentstatus'), nullable=False),
    sa.Column('assignment_note', sa.Text(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_assignments_assigned_at'), 'report_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_report_assignments_department_id'), 'report_assignments', ['department_id'], unique=False)
    op.create_index(op.f('ix_report_assignments_due_date'), 'report_assignments', ['due_date'], unique=False)
    op.create_index(op.f('ix_report_assignments_id'), 'report_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_report_assignments_report_id'), 'report_assignments', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_assignments_status'), 'report_assignments', ['status'], unique=False)
    op.create_table('report_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['report_comments.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_comments_id'), 'report_comments', ['id'], unique=False)
    op.create_index(op.f('ix_report_comments_report_id'), 'report_comments', ['report_id'], unique=False)
    op.create_table('report_followers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_followers_id'), 'report_followers', ['id'], unique=False)
    op.create_index(op.f('ix_report_followers_report_id'), 'report_followers', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_followers_user_id'), 'report_followers', ['user_id'], unique=False)
    op.create_table('report_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media_files.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_media_id'), 'report_media', ['id'], unique=False)
    op.create_index(op.f('ix_report_media_media_id'), 'report_media', ['media_id'], unique=False)
    op.create_index(op.f('ix_report_media_report_id'), 'report_media', ['report_id'], unique=False)
    op.create_table('report_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_votes_id'), 'report_votes', ['id'], unique=False)
    op.create_index(op.f('ix_report_votes_report_id'), 'report_votes', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_votes_user_id'), 'report_votes', ['user_id'], unique=False)
    op.create_table('assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='assignmentstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='assignmentstatus'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['report_assignments.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_history_assignment_id'), 'assignment_history', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_history_created_at'), 'assignment_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_assignment_history_id'), 'assignment_history', ['id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_assignment_history_id'), table_name='assignment_history')
    op.drop_index(op.f('ix_assignment_history_created_at'), table_name='assignment_history')
    op.drop_index(op.f('ix_assignment_history_assignment_id'), table_name='assignment_history')
    op.drop_table('assignment_history')
    op.drop_index(op.f('ix_report_votes_user_id'), table_name='report_votes')
    op.drop_index(op.f('ix_report_votes_report_id'), table_name='report_votes')
    op.drop_index(op.f('ix_report_votes_id'), table_name='report_votes')
    op.drop_table('report_votes')
    op.drop_index(op.f('ix_report_media_report_id'), table_name='report_media')
    op.drop_index(op.f('ix_report_media_media_id'), table_name='report_media')
    op.drop_index(op.f('ix_report_media_id'), table_name='report_media')
    op.drop_table('report_media')
    op.drop_index(op.f('ix_report_followers_user_id'), table_name='report_followers')
    op.drop_index(op.f('ix_report_followers_report_id'), table_name='report_followers')
    op.drop_index(op.f('ix_report_followers_id'), table_name='report_followers')
    op.drop_table('report_followers')
    op.drop_index(op.f('ix_report_comments_report_id'), table_name='report_comments')
    op.drop_index(op.f('ix_report_comments_id'), table_name='report_comments')
    op.drop_table('report_comments')
    op.drop_index(op.f('ix_report_assignments_status'), table_name='report_assignments')
    op.drop_index(op.f('ix_report_assignments_report_id'), table_name='report_assignments')
    op.drop_index(op.f('ix_report_assignments_id'), table_name='report_assignments')
    op.drop_index(op.f('ix_report_assignments_due_date'), table_name='report_assignments')
    op.drop_index(op.f('ix_report_assignments_department_id'), table_name='report_assignments')
    op.drop_index(op.f('ix_report_assignments_assigned_at'), table_name='report_assignments')
    op.drop_table('report_assignments')
    op.drop_index(op.f('ix_report_activities_report_id'), table_name='report_activities')
    op.drop_index(op.f('ix_report_activities_id'), table_name='report_activities')
    op.drop_table('report_activities')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_index(op.f('ix_user_notification_settings_id'), table_name='user_notification_settings')
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_category'), table_name='reports')
    op.drop_index('idx_reports_location', table_name='reports', postgresql_using='gist')
    op.drop_table('reports')
    op.drop_index(op.f('ix_media_files_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_file_type'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_created_at'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_department_members_user_id'), table_name='department_members')
    op.drop_index(op.f('ix_department_members_id'), table_name='department_members')
    op.drop_index(op.f('ix_department_members_department_id'), table_name='department_members')
    op.drop_table('department_members')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_location', table_name='users', postgresql_using='gist')
    op.drop_table('users')
    op.drop_index(op.f('ix_transport_facilities_osm_id'), table_name='transport_facilities')
    op.drop_index(op.f('ix_transport_facilities_id'), table_name='transport_facilities')
    op.drop_index(op.f('ix_transport_facilities_facility_type'), table_name='transport_facilities')
    op.drop_index('idx_transport_facilities_location', table_name='transport_facilities', postgresql_using='gist')
    op.drop_table('transport_facilities')
    op.drop_index(op.f('ix_streets_osm_id'), table_name='streets')
    op.drop_index(op.f('ix_streets_name'), table_name='streets')
    op.drop_index(op.f('ix_streets_id'), table_name='streets')
    op.drop_index(op.f('ix_streets_highway_type'), table_name='streets')
    op.drop_index('idx_streets_geometry', table_name='streets', postgresql_using='gist')
    op.drop_table('streets')
    op.drop_index(op.f('ix_report_categories_id'), table_name='report_categories')
    op.drop_index(op.f('ix_report_categories_code'), table_name='report_categories')
    op.drop_table('report_categories')
    op.drop_index(op.f('ix_public_facilities_osm_id'), table_name='public_facilities')
    op.drop_index(op.f('ix_public_facilities_name'), table_name='public_facilities')
    op.drop_index(op.f('ix_public_facilities_id'), table_name='public_facilities')
    op.drop_index(op.f('ix_public_facilities_category'), table_name='public_facilities')
    op.drop_index('idx_public_facilities_location', table_name='public_facilities', postgresql_using='gist')
    op.drop_table('public_facilities')
    op.drop_index(op.f('ix_pois_subcategory'), table_name='pois')
    op.drop_index(op.f('ix_pois_osm_id'), table_name='pois')
    op.drop_index(op.f('ix_pois_name'), table_name='pois')
    op.drop_index(op.f('ix_pois_id'), table_name='pois')
    op.drop_index(op.f('ix_pois_category'), table_name='pois')
    op.drop_index('idx_pois_location', table_name='pois', postgresql_using='gist')
    op.drop_table('pois')
    op.drop_index(op.f('ix_notification_templates_type'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_incidents_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_title'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_started_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_active'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index('idx_incidents_location', table_name='incidents', postgresql_using='gist')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_environmental_data_measured_at'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_id'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_district_id'), table_name='environmental_data')
    op.drop_index(op.f('ix_environmental_data_data_type'), table_name='environmental_data')
    op.drop_table('environmental_data')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_location_geom'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index('idx_entities_location_geom', table_name='entities', postgresql_using='gist')
    op.drop_table('entities')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_buildings_osm_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_name'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_index(op.f('ix_buildings_building_type'), table_name='buildings')
    op.drop_index('idx_buildings_geometry', table_name='buildings', postgresql_using='gist')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_administrative_boundaries_osm_id'), table_name='administrative_boundaries')
    op.drop_index(op.f('ix_administrative_boundaries_name'), table_name='administrative_boundaries')
    op.drop_index(op.f('ix_administrative_boundaries_id'), table_name='administrative_boundaries')
    op.drop_index(op.f('ix_administrative_boundaries_admin_level'), table_name='administrative_boundaries')
    op.drop_index('idx_administrative_boundaries_geometry', table_name='administrative_boundaries', postgresql_using='gist')
    op.drop_table('administrative_boundaries')
    # ### end Alembic commands ###

